version: '3'
services:

  elasticsearch:
    image: elasticsearch:6.8.2
    volumes:
      - ./data_elasticsearch:/usr/share/elasticsearch/data

  postgres:
    image: postgres
    volumes:
      - ./data_postgres:/usr/share/elasticsearch/data
  django:
    container_name: django
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - postgres
      - elasticsearch
